image: Visual Studio 2017

build_script:
  - ps: .\build.ps1

artifacts:
  - path: ./out/*.nupkg

nuget:
  project_feed: true

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true

  skip_symbols: false
  artifact: /.*\.nupkg$/
  api_key:
    secure: ljl/r7XeQm+KBzR7pm1OOW4+YcDUsYiWlr9jWFztMh/8/orG4V9ylTi+P1jGME7g
