dist: trusty
language: csharp

mono: latest

# Needed by GitVersion
git:
  depth: 9999999

branches:
  only:
    - develop
    - master

# We need the .NET Core 2.1 (preview 1) SDK to build. Travis doesn't know how to install this yet.
before_install:
  - echo 'Installing .NET Core...'
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get -qq update
  - sudo apt-get install -y jq dotnet-sdk-2.1.300-preview1-008174

script:
  - /bin/bash ./build-ci.sh
  - /bin/bash ./publish-ci.sh

env:
  NUGET_API_KEY:
    secure: "GbdCqtw8PTNk7Jzc4kXKQbGJdnRg1C3DEaT2a8soh0P6qKdo+0WIAhj+f+MLohXc2MQ0TjrPSKHqN8GLj1ss+ZjXKils8oWjBIC90RmexndX520VOCbtCSqOfiLEdhG51cfj4tHdYs9aZtHoEyNknGXWgj8N0RJg55H8Q9VZU1Xzo6eysJwdL/aqHddCBeXb5HWHo9o3Wdy5G8FsROwiaRSSC2G6s+3tRQca8nVvOoZA8yzfKy8cVJtWc8D1pjRV3sX9fkm5LdRbngizPdc55Z9RK5Lz5KA1yFNzDQABAiS4jH9E/QrcKYdkav+0uZxWHwrCNGV24TdLBDgIzdjfjRKQFPWKNBY3wZ58MzFk2DAJmn0GBG1Hy36S9oddCgJAvYkhPUFToiiOv383v7kyDY7nZhvttHeQ4lihkDN1ofDHp45vKIvb6UZz8PVSSFqNDGYpXrO3fBCpz33VMkpi+V96L7R0ppz+FgutRZkeYN5VRrooMa3W0QYw+ZaxLNqr7jN8pW9pmxAOt1+/zN76J98nZe+IT8afKcv7N7DkrSk2b6kRu1MvSh1qJBOIxlchMNIsP5bu7dWNL12tKxmIOzQhaEbPX1Xu7u2+TxsSqVi6pAEXZHJ6cBCFU1mdev4cAPDXD1vgxlB0olor4uXnN1+g7Tu/aoGyMcgLFwUKzJM="
  MYGET_API_KEY:
    secure: "CBkrZli91ex2qAK2PI7t0i1qVmFBN3dV9syAqJ4wAidEP2I8Er2BBGPfPQD0fmDDvpvZa7RroUOQpL91qKAjMjM/RErgp5dxst6sriXF2wdipMWSnlsGqDp+TQlo6RkA1rnSj0OFHAQNJYlWplj7tsQ43dBl1kQuK0uGdohNNaznoyk7SYqZJBzhoakqQx/rr8QE8VnzUzJl13BQ17AtTiVfn5I6JaE1FLP7RKoAIK4XH51aKkLNtP0R3TYs5jmu9yKPwIp0Rdkll7Y+rLNgw+vhwkxui5k2fPaUhyzXcNSrPK274n13CgUuYI+uK0FAFSVcIzr4O+pL839jNDdXAiBPl3wzy0FzwHleFSQBZZIKNGKIODGYh857wmsE7DUTriz19z8u8rlr9VcBpiFaholupQSANfHN98N2+WOQt3kXiTn/2lGctkG4Nc9Q6bsCVpwE4I0M/aEZkZyaZk+nhWRYmWVoNZfqnsFZRrIkl9wnjLrA75N2CslFIm14iQrLQjlLdMxR+5Rm9FRPZaI9ipJl20D+kDDXJQEk8QgVNV5iniNUK89aepKxUDqQO4vNNLqYemBDBBcbqZ+ytpn2kiC1k1M02ZC3PQ5NzJqB2x+Uij+tc6QJUUlqBSdtybirZNbE0A+vQYc3olI4u/dmdmtm8HoxPl5QogNVVNxIUC0="
