dist: trusty
language: csharp

mono: latest
dotnet: 2.1.300-preview1-008174

# Needed by GitVersion
git:
  depth: 9999999

branches:
  only:
    - feature/websockets

addons:
  apt:
    packages:
    - jq

script:
  - ./build-ci.sh

env:
  global:
    secure: h8VflQcXJ34XKlCrPhDdTNbEotG/AjXi/+JjMQ8Bo79p27kwofgIfxz8AUjbS60gO+2AqyNK8UJodHZ6Cw9QRq7xqNBwoQRIB8jbwOkVWv/GpQ9ehGC4AoNuvkl/2/vjNnFtCRSONVJNn/bVxDrASj038L/XNFzdyMvyIYvadkygcNL8v70JaoMd4b5J2vW69d0QTKfhDFBNmUww7rgT79RKEvNIOTazmNJccu2qLwPOAP0C0FtitJUqBCO9rAbmWLahL7eUgBS78g8GqJ/7t5t8kPTmcAPfspPJCosu2kL1rsg62NiwXTxDWH1FLH2p2m7kF+48ssXqEdiNze95vth1YwRQUX6hVa0lp7m04gNSEWd66FURC7c8sjYGdDvTX8ailRDWA5ft3rrw5eidayTIXbJRI5uKt39eTRmd/0Gf0PIwJShoVzRvjMRVtJ6OL17YNF4vUQTWc6SwD6UoDcMlnb6c8vyE8tsQv+OUOCt0LrNm9QV2Oe9JkyOSwuO/ie7drebtB82DuRKgbiFKO0CmtZPvSjvvo/TYxZF0lA7dcaNMfucoQKRdNNYQHh6iahYR2lD7vtHEI9UWcmBBMNz6JAwDRGB/UZtNIM7tDKBsSb3XxCJMYinph8KHfU9xS5q1BIj/AfVLVzfFGCRo/93l/OCWtf4wCIexOlcoJbQ=
